---
- name: Setup java application server
  hosts: app001

  user: vagrant
  bacome: yes

  vars:
    - dbhosts: "db01"
    - dbname: "notes"
    - dbusername: "notesapp"
    - dbpassword: "devopsdb"
  tasks:
    - name: Setup lab ansible hosts
      lineinfile: 
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 192.168.1.2 control-node
        - 192.168.1.3 app01
        - 192.168.1.4 db01
    - name: Add app user
      user:
        name: app
        comment: Application user
        uid: 500
    - name: Maven download
      get_url:
        url: https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.1.0/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/apache-maven-3.1.0-bin.tar.gz
    - name: Unzip maven package
      ansible.builtin.unarchive:
        src: /opt/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/
        remote_src: yes
    - name: Java instalation
      yum:
        name: java-1.8.0-openjdk
        state: latest
    - name: App folders creation
      file:
        path: /opt/notes
        state: directory
        owner: app
        group: app
    - name: Install git client
      yum:
        name: git
        state: latest
    - name: Clonning Notes Repository - app
      git:
        repo: "https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git"
        dest: /opt/notes
        clone: yes
        force: yes
    - name: Setup pom.xml file with repositoriies maven center
      template:
        src: pom.xml
        dest: /opt/notes/pom.xml
    - name: Setup properties file to database layer
      template: 
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties
    - name: Generate App package
      command: mvn -f /opt/notes/pom.yml package
      become_user: app
    - name: Register package current version
      shell:
        cmd: mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['
        chdir: /opt/notes/
      register: app_version
    - name: Setup Systemd service
      template:
        src: etc/systemd/system/notes.service
        dest: /etc/systemd/system/notes.service
      notify: reload daemon
    - name: Start notes service
      service:
        name: notes
        state: restarted
  role:
    - setup-derault-so
  handlers:
    - name: reload app
      systemd:
        state: restarted
        daemon_reload: yes
        name: 'notes'
    - name: reload daemon
    systemd:
      daemon_reexec: yes





