---
- name: Setup Databaseserver
  hosts: db01

  user: vagrant
  become: yes
  vars_files: 
    - vars/main.yml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "devopsdb"
  roles:
    - setup-default-so
    - role: geerlingguy.mysql
    